### ISSUE TITLE
Some/bunch of REMA/etc pages need REME info fixed

### ISSUE THREAD

**Issue by ithorien** [posimagi/bg-wiki-dark-mode#23]
Looks like it's affecting most, haven't checked every one-
![2023-04-20 15 52 04](https://user-images.githubusercontent.com/4006255/233485874-0bfd2eea-7b08-4e1a-92e0-d8ad87a4b428.png)
 TYTY!<3<3

**Comment by posimagi** [comment]
This one should be an easy fix.

**Comment by posimagi** [comment]
This might only be an issue for instruments and shields, I believe other weapon types are using the `Aftermath Weapon` template which has been updated for dark mode.

**Comment by posimagi** [comment]
Fixed for Daurdabla 99 II, and extended the template with the option `shieldorinstrument` to make the existing REMA template display correctly for weapons that cannot be swung. Will go through the other pages and swap out the template.

<img width="807" alt="image" src="https://user-images.githubusercontent.com/1747598/233497451-1ed3d6c3-5c65-4776-8e2f-95db779dd0bc.png">

**Comment by posimagi** [comment]
Fixed for Daurdabla pages. If you'd like, you can fix the other shields and instruments yourself by simply replicating [this change](https://www.bg-wiki.com/index.php?title=Daurdabla_%28Level_85%29&type=revision&diff=677761&oldid=423610) for all of them. The change consists of deleting the entire raw "REME Information" table and replacing it with this template:

```
{{Aftermath Weapon
|weapon=Daurdabla
|ws=None
|empyrean=Yes
|shieldorinstrument=Yes
}}
```

If you'd like to do this yourself that'd be awesome, otherwise one of the other editors will get around to it eventually.

Applicable pages should be:
Aegis (all versions)
Gjallarhorn (all versions)
Ochain (all versions)
~~Daurdabla (all versions)~~ done as proof-of-concept

Thanks!

**Comment by posimagi** [comment]
Neviskio is taking care of the remaining pages.
